### ISSUE TITLE
Tests run from IDE don't work from ^5.0.0, works alright in ^4.0.0

### ISSUE THREAD

**Issue by raghavan85** [americanexpress/amex-jest-preset-react#2]
Tests run from IDE don't work from ^5.0.0, works alright in ^4.0.0.

In ^4.0.0:

[image-redacted]

But with ^5.0.0:

[image-redacted]

The runs without any issues when run from a command line.

**Comment by anescobar1991** [comment]
@raghavan85 can we go through internal channels to discuss this and fix internally if needed before putting it out on github?
